name: Deploy .NET API to IIS

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          include-prerelease: false
          use-msi: true

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Stop IIS
        run: iisreset /stop

      - name: Deploy Files
        run: |
          Remove-Item "C:\inetpub\wwwroot\Deploy\*" -Recurse -Force -ErrorAction Ignore
          Copy-Item "publish\*" "C:\inetpub\wwwroot\Deploy\" -Recurse

      - name: Start IIS
        run: iisreset /start